name: codecollab-auth

services:
  migrations:
    image: ghcr.io/morozkoart/codecollab/auth-migrations:latest
    container_name: codecollab-auth-migrations
    env_file:
      - ../../.env
    environment:
      - GOOSE_DRIVER=postgres
      - GOOSE_DBSTRING=host=${POSTGRES_HOST} port=${POSTGRES_PORT} user=${POSTGRES_USER} password=${POSTGRES_PASSWORD} dbname=${POSTGRES_DB} sslmode=${POSTGRES_SSLMODE}
    networks:
      - codecollab-network
    command: up --allow-missing

  auth:
    image: ghcr.io/morozkoart/codecollab/auth:latest
    container_name: codecollab-auth
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
      - "${GRPC_PORT}:${GRPC_PORT}"
    environment:
      # переменная для го приложения, го приложение берет env переменные напрямую из ОС, без env файла,
      # env файл передаем только в контейнер, чтобы записать переменные в ОС
      - "WITH_ENV_FILE=0"
    env_file:
      - ../../.env
    networks:
      - codecollab-network
    depends_on:
      migrations:
        condition: service_completed_successfully
    restart: unless-stopped

networks:
  codecollab-network:
    external: true
    name: codecollab-network